[workspace]
members = [
  "crates/aqami-cli",
  "crates/aqami-spec"
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
anyhow = "*"
clap = { version = "*", features = ["derive"] }
jsonschema = { version = "*", default-features = false }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
thiserror = "*"
yaml_serde = "*"
