[package]
name = "aqami-cli"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
aqami-codegen = { path = "../aqami-codegen" }
aqami-spec = { path = "../aqami-spec" }
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
